apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: kube-cosme-cluster
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app-container
          image: cosmeaf/cosmeaf_image:latest
          ports:
            - containerPort: 3000
